server:
  port: 8088
#  ssl:
#    key-store: tomcat.keystore
#    key-password: 123456
#    key-store-type: JKS
#    key-alias: tomcat
spring:
  datasource:
    #url: jdbc:mysql://192.168.1.108:3306/security_test?characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=true
    url: jdbc:sqlserver://127.0.0.1:1433;DatabaseName=user_db
    username: root
    password: root
    initial-size: 1  
    min-idle: 1  
    max-active: 20  
    test-on-borrow: true  
    max-wait: 60000  
    time-between-eviction-runs-millis: 60000  
    min-evictable-idle-time-millis: 300000  
    validation-query: SELECT 1
    test-While-Idle: true  
    test-on-return: false  
    pool-prepared-statements: false  
    max-pool-prepared-statement-per-connection-size: 20  
    filters: stat,wall,log4j,config
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      authentication-database: admin
      database: security_test
      username: root
      password: root
#============== redis ===================
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 0
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 1
#============== kafka ===================
kafka:
  enabled: false
  consumer:
    zookeeper-connect: 127.0.0.1:2181
    servers: 127.0.0.1:9092
    topic: test,test2
    group-id: test
    concurrency: 2
    session-timeout: 6000
    enable-auto-commit: true
    auto-commit-interval: 100
    auto-offset-reset: latest
  producer:
    servers: 127.0.0.1:9092
    retries: 0
    batch-size: 4096
    linger: 1
    buffer-memory: 40960
